import { Gender, UserRole } from '../users/enums/users.enums';

export interface ISeedUser {
  name: string;
  email: string;
  password: string;
  about?: string;
  birthdate?: Date;
  gender?: Gender;
  avatar?: string;
  role: UserRole;
}

export const seedTestUsers: ISeedUser[] = [
  {
    name: 'Ivan Ivanov',
    email: 'ivan@test.local',
    password: 'Password1',
    role: UserRole.USER,
  },
  {
    name: 'Aleksandr Alexandrov',
    email: 'Aleksandr@test.local',
    password: 'Password1',
    role: UserRole.USER,
  },
  {
    name: 'Александр Иванов',
    email: 'alexander.ivanov@test.local', // Generated email
    password: 'Password1',
    about: 'Профессиональный маркетолог с 10-летним опытом',
    birthdate: new Date('1990-05-15'),
    gender: Gender.MALE,
    avatar:
      'https://avatars.mds.yandex.net/get-yapic/28439/c2C5tZ34ITInGSxIVJrWaPMZiA-1/orig',
    role: UserRole.USER,
  },
  {
    name: 'Мария Петрова',
    email: 'maria.petrova@test.local',
    password: 'Password1',
    about: 'Фотограф с художественным образованием',
    birthdate: new Date('1985-11-22'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/b8/e6/3b/b8e63b99cd3b38474fe11eb98f3045fd.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Дмитрий Смирнов',
    email: 'dmitry.smirnov@test.local',
    password: 'Password1',
    about: 'Преподаватель английского с кембриджской сертификацией',
    birthdate: new Date('1982-08-30'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/736x/c1/d3/3d/c1d33d6901e0d4082409830c683b63ea.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Анна Козлова',
    email: 'anna.kozlova@test.local',
    password: 'Password1',
    about: 'Дизайнер интерьеров с европейским опытом',
    birthdate: new Date('1993-03-12'),
    gender: Gender.FEMALE,
    avatar: 'https://stihi.ru/pics/2025/07/03/5421.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Екатерина Волкова',
    email: 'ekaterina.volkova@test.local',
    password: 'Password1',
    about: 'Сертифицированный инструктор по йоге и медитации',
    birthdate: new Date('1987-04-05'),
    gender: Gender.FEMALE,
    avatar:
      'https://avatars.mds.yandex.net/get-shedevrum/12421798/img_7f6287dcfefb11ee87c89608ae710c1d/orig',
    role: UserRole.USER,
  },
  {
    name: 'Иван Николаев',
    email: 'ivan.nikolaev@test.local',
    password: 'Password1',
    about: 'Финансовый консультант и инвестор',
    birthdate: new Date('1991-07-19'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/originals/65/05/21/6505211baace954cdcc8b4c97a2e41f3.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Ольга Семенова',
    email: 'olga.semenova@test.local',
    password: 'Password1',
    about: 'Шеф-повар итальянской кухни',
    birthdate: new Date('1988-09-28'),
    gender: Gender.FEMALE,
    avatar:
      'https://avatars.mds.yandex.net/get-shedevrum/11270697/img_bdb3217b091c11efb1e4425307c1c5e5/orig',
    role: UserRole.USER,
  },
  {
    name: 'Артем Васильев',
    email: 'artem.vasiliev@test.local',
    password: 'Password1',
    about: 'Профессиональный видеограф',
    birthdate: new Date('1984-12-03'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/736x/7c/ee/e8/7ceee832d7f2fca5c3aea32c818623bf.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Наталья Кузнецова',
    email: 'natalia.kuznetsova@test.local',
    password: 'Password1',
    about: 'Лайф-коуч и консультант по осознанности',
    birthdate: new Date('1995-02-14'),
    gender: Gender.FEMALE,
    avatar: 'https://stihi.ru/pics/2024/05/31/137.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Сергей Попов',
    email: 'sergey.popov@test.local',
    password: 'Password1',
    about: 'Мастер по ремонту бытовой техники',
    birthdate: new Date('1980-06-25'),
    gender: Gender.MALE,
    avatar:
      'https://avatars.mds.yandex.net/get-shedevrum/12421798/img_51aa6f68ef8111eea76b3aa34a603afe/orig',
    role: UserRole.USER,
  },
  {
    name: 'Алина Морозова',
    email: 'alina.morozova@test.local',
    password: 'Password1',
    about: 'Профессиональный художник и иллюстратор',
    birthdate: new Date('1992-09-14'),
    gender: Gender.FEMALE,
    avatar: 'https://stihi.ru/pics/2025/06/06/1045.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Павел Громов',
    email: 'pavel.gromov@test.local',
    password: 'Password1',
    about: 'Специалист по китайской медицине',
    birthdate: new Date('1986-11-30'),
    gender: Gender.MALE,
    avatar: 'https://stihi.ru/pics/2024/03/30/7855.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Юлия Лебедева',
    email: 'yulia.lebedev@test.local',
    password: 'Password1',
    about: 'Специалист по подбору персонала',
    birthdate: new Date('1994-04-18'),
    gender: Gender.FEMALE,
    avatar:
      'https://masterpiecer-images.s3.yandex.net/fb3a11eb54b611eeaa384659bdca6a39:upscaled',
    role: UserRole.USER,
  },
  {
    name: 'Михаил Соколов',
    email: 'mikhail.sokolov@test.local',
    password: 'Password1',
    about: 'Финансовый аналитик в международной компании',
    birthdate: new Date('1983-07-22'),
    gender: Gender.MALE,
    avatar:
      'https://masterpiecer-images.s3.yandex.net/3011fc6e7e4411ee8071ceda526c50ab:upscaled',
    role: UserRole.USER,
  },
  {
    name: 'Елена Воробьева',
    email: 'elena.vorobieva@test.local',
    password: 'Password1',
    about: 'Профессиональный организатор пространств',
    birthdate: new Date('1989-12-08'),
    gender: Gender.FEMALE,
    avatar:
      'https://img.goodfon.com/wallpaper/nbig/e/83/chest-girl-model-panties-tummy-figure-underwear-legs-on-th-4.webp',
    role: UserRole.USER,
  },
  {
    name: 'Андрей Новиков',
    email: 'andrey.novikov@test.local',
    password: 'Password1',
    about: 'Сертифицированный тренер по кроссфиту',
    birthdate: new Date('1990-03-25'),
    gender: Gender.MALE,
    avatar:
      'https://avatars.dzeninfra.ru/get-zen_doc/9827869/pub_64cb7c0e926aa97cdaf192af_64cb7cf4f24c176c51068510/scale_1200',
    role: UserRole.USER,
  },
  {
    name: 'Оксана Кузнецова',
    email: 'oksana.kuznetsova@test.local',
    password: 'Password1',
    about: 'Преподаватель французского языка',
    birthdate: new Date('1985-06-17'),
    gender: Gender.FEMALE,
    avatar:
      'https://masterpiecer-images.s3.yandex.net/f15f38125dfd11ee936a6a0259d7362a:upscaled',
    role: UserRole.USER,
  },
  {
    name: 'Денис Петров',
    email: 'denis.petrov@test.local',
    password: 'Password1',
    about: 'IT-рекрутер в международной компании',
    birthdate: new Date('1988-10-11'),
    gender: Gender.MALE,
    avatar:
      'https://avatars.mds.yandex.net/get-shedevrum/12155741/img_17e57411fda811ee885a6a067d72cb03/orig',
    role: UserRole.USER,
  },
  {
    name: 'Татьяна Михайлова',
    email: 'tatyana.mikhailova@test.local',
    password: 'Password1',
    about: 'Диетолог и нутрициолог',
    birthdate: new Date('1993-01-30'),
    gender: Gender.FEMALE,
    avatar:
      'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_67acb410ee961d5e4e0c8259_67acb5857ef27a7301872d35/scale_1200',
    role: UserRole.USER,
  },
  {
    name: 'Артур Яковлев',
    email: 'artur.yakovlev@test.local',
    password: 'Password1',
    about: 'Профессиональный звукорежиссер',
    birthdate: new Date('1987-08-09'),
    gender: Gender.MALE,
    avatar:
      'https://masterpiecer-images.s3.yandex.net/4c63586d7f0011ee949a5696910b1137:upscaled',
    role: UserRole.USER,
  },
  {
    name: 'Виктория Семенова',
    email: 'viktoria.semenova@test.local',
    password: 'Password1',
    about: 'Специалист по скорочтению и развитию памяти',
    birthdate: new Date('1991-05-19'),
    gender: Gender.FEMALE,
    avatar:
      'https://avatars.mds.yandex.net/get-shedevrum/12363575/cb6e98e3cc8f11ee9a579a79ffaf5bd2/orig',
    role: UserRole.USER,
  },
  {
    name: 'Глеб Федоров',
    email: 'gleb.fedorov@test.local',
    password: 'Password1',
    about: 'Эксперт по домашним растениям',
    birthdate: new Date('1984-12-03'),
    gender: Gender.MALE,
    avatar:
      'https://masterpiecer-images.s3.yandex.net/7cc3ec2bb06d11ee8a563abd0be4d755:upscaled',
    role: UserRole.USER,
  },
  {
    name: 'Ксения Павлова',
    email: 'ksenia.pavlova@test.local',
    password: 'Password1',
    about: 'Коуч по личностному развитию',
    birthdate: new Date('1989-07-28'),
    gender: Gender.FEMALE,
    avatar:
      'https://masterpiecer-images.s3.yandex.net/af7eff9778ea11ee93f7963c1ee369ba:upscaled',
    role: UserRole.USER,
  },
  {
    name: 'Роман Козлов',
    email: 'roman.kozlov@test.local',
    password: 'Password1',
    about: 'Профессиональный бармен',
    birthdate: new Date('1986-02-15'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/originals/a1/6a/f6/a16af6cdac7be9473b6e19acd97e7cec.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Анастасия Власова',
    email: 'anastasia.vlasova@test.local',
    password: 'Password1',
    about: 'Специалист по японскому языку',
    birthdate: new Date('1993-11-20'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/4b/5c/2d/4b5c2dae9c3818114c40fcd1d954d3b9.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Игорь Медведев',
    email: 'igor.medvedev@test.local',
    password: 'Password1',
    about: 'Специалист по ремонту компьютеров',
    birthdate: new Date('1981-09-05'),
    gender: Gender.MALE,
    avatar:
      'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_65946b5816f1ad2e391f7745_6594711b4fb36f2999a4d56c/scale_1200',
    role: UserRole.USER,
  },
  {
    name: 'Светлана Крылова',
    email: 'svetlana.krylova@test.local',
    password: 'Password1',
    about: 'Детский психолог',
    birthdate: new Date('1988-04-12'),
    gender: Gender.FEMALE,
    avatar: 'https://rusradio.ru/uploads/87/ad/faafbf2903ad59b0b84079468302.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Вадим Белов',
    email: 'vadim.belov@test.local',
    password: 'Password1',
    about: 'Мастер по ремонту мебели',
    birthdate: new Date('1983-06-30'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/736x/1c/4e/29/1c4e290f01141c83de7a3e4f526e3f36.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Людмила Степанова',
    email: 'lyudmila.stepanova@test.local',
    password: 'Password1',
    about: 'Преподаватель испанского языка',
    birthdate: new Date('1979-10-18'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/6c/e6/98/6ce6987eddb90d15e291e4411b5fbaea.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Григорий Давыдов',
    email: 'grigory.davydov@test.local',
    password: 'Password1',
    about: 'Специалист по китайской каллиграфии',
    birthdate: new Date('1985-01-25'),
    gender: Gender.MALE,
    avatar:
      'https://avatars.mds.yandex.net/get-shedevrum/12151221/img_aa7a3734f0be11ee970ffa438e8a26f5/orig',
    role: UserRole.USER,
  },
  {
    name: 'Зоя Алексеева',
    email: 'zoya.alekseeva@test.local',
    password: 'Password1',
    about: 'Специалист по осознанному питанию',
    birthdate: new Date('1990-08-14'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/d9/88/ac/d988ace7d3bff035bdff4eafaae0fb57.webp',
    role: UserRole.USER,
  },
  {
    name: 'Максим Орлов',
    email: 'maxim.orlov@test.local',
    password: 'Password1',
    about: 'Эксперт по тайм-менеджменту',
    birthdate: new Date('1987-03-22'),
    gender: Gender.MALE,
    avatar: 'https://cdn1.flamp.ru/711b8b3234f41e9f68d629229ff27f14.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Элина Сорокина',
    email: 'elina.sorokina@test.local',
    password: 'Password1',
    about: 'Флорист-декоратор',
    birthdate: new Date('1994-11-05'),
    gender: Gender.FEMALE,
    avatar:
      'https://avatars.dzeninfra.ru/get-zen_doc/5218815/pub_63ead032afb29857ce316e07_63ead1016f86f30cddf567cf/scale_1200',
    role: UserRole.USER,
  },
  {
    name: 'Станислав Баранов',
    email: 'stanislav.baranov@test.local',
    password: 'Password1',
    about: 'Инструктор по функциональному тренингу',
    birthdate: new Date('1982-07-30'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/736x/61/fe/28/61fe28c3f1dda2a9879f0e2d36ed99cc.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Вероника Зайцева',
    email: 'veronika.zaytseva@test.local',
    password: 'Password1',
    about: 'Преподаватель актерского мастерства',
    birthdate: new Date('1989-04-17'),
    gender: Gender.FEMALE,
    avatar: 'https://i.ytimg.com/vi/ZV2TnBohs6A/maxresdefault.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Арсений Гусев',
    email: 'arseny.gusev@test.local',
    password: 'Password1',
    about: 'Специалист по немецкому языку',
    birthdate: new Date('1983-12-08'),
    gender: Gender.MALE,
    avatar:
      'https://p0.piqsels.com/preview/217/979/788/man-male-smile-portrait.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Диана Егорова',
    email: 'diana.egorova@test.local',
    password: 'Password1',
    about: 'Специалист по арт-терапии',
    birthdate: new Date('1992-02-11'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/3c/9f/2c/3c9f2cb07b98e34f4cbe77e02e0f20de.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Ярослав Комаров',
    email: 'yaroslav.komarov@test.local',
    password: 'Password1',
    about: 'IT-рекрутер в международной компании',
    birthdate: new Date('1986-06-25'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/originals/7d/ca/be/7dcabe92370fff0c6489aba65af5dab2.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Арина Фомина',
    email: 'arina.fomina@test.local',
    password: 'Password1',
    about: 'Дизайнер интерфейсов',
    birthdate: new Date('1995-09-03'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/ed/92/9e/ed929e87ab35ddc754ae50feae0228db.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Георгий Данилов',
    email: 'georgy.danilov@test.local',
    password: 'Password1',
    about: 'Мастер по ремонту бытовой техники',
    birthdate: new Date('1984-10-19'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/736x/ee/71/74/ee7174feb2450d8f79f30e6f0e31c411.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Лидия Тихонова',
    email: 'lidia.tikhonova@test.local',
    password: 'Password1',
    about: 'Специалист по ментальной арифметике',
    birthdate: new Date('1988-05-28'),
    gender: Gender.FEMALE,
    avatar:
      'https://yobte.ru/uploads/posts/2019-11/devushki-s-golubymi-glazami-s-rusymi-volosami-41-foto-3.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Руслан Савельев',
    email: 'ruslan.saveliev@test.local',
    password: 'Password1',
    about: 'Профессиональный фотограф дикой природы',
    birthdate: new Date('1981-11-15'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/736x/aa/01/39/aa0139b260f3edebb46dc1bd2e7a1117.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Алиса Герасимова',
    email: 'alisa.gerasimova@test.local',
    password: 'Password1',
    about: 'Преподаватель китайского языка',
    birthdate: new Date('1993-07-07'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/c0/62/63/c0626354ac57b138ec7a113c7353f014.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Илья Дмитриев',
    email: 'ilya.dmitriev@test.local',
    password: 'Password1',
    about: 'Специалист по ремонту электроники',
    birthdate: new Date('1987-12-22'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/originals/e4/79/de/e479de8cae918f5ad91076bd3dfe7078.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Валерия Соболева',
    email: 'valeria.soboleva@test.local',
    password: 'Password1',
    about: 'Сертифицированный коуч по отношениям',
    birthdate: new Date('1990-04-01'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/70/a9/2f/70a92f8895863a5c544b71d49c3a5dea.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Тимур Власов',
    email: 'timur.vlasov@test.local',
    password: 'Password1',
    about: 'Профессиональный бармен и сомелье',
    birthdate: new Date('1985-08-09'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/originals/b4/75/db/b475db4f81386bdf37dd4cf49bbc9f60.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Ульяна Котова',
    email: 'ulyana.kotova@test.local',
    password: 'Password1',
    about: 'Художник по акварели',
    birthdate: new Date('1994-01-26'),
    gender: Gender.FEMALE,
    avatar:
      'https://i.pinimg.com/originals/cf/4f/d4/cf4fd4743158b3801d6b6fa47ea3ba8d.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Даниил Жуков',
    email: 'daniel.zhukov@test.local',
    password: 'Password1',
    about: 'Специалист по финансовой грамотности',
    birthdate: new Date('1989-06-13'),
    gender: Gender.MALE,
    avatar:
      'https://www.churchofjesuschrist.org/bc/content/shared/content/images/gospel-library/manual/PD60004369/iStock-157403823.jpg',
    role: UserRole.USER,
  },
  {
    name: 'Кира Новикова',
    email: 'kira.novikova@test.local',
    password: 'Password1',
    about: 'Преподаватель испанского языка',
    birthdate: new Date('1991-03-08'),
    gender: Gender.FEMALE,
    avatar: 'https://wallpaper.forfun.com/fetch/4a/4a18c32ad3e38db6ab287a7fd06185d4.jpeg',
    role: UserRole.USER,
  },
  {
    name: 'Артур Тимофеев',
    email: 'artur.timofeev@test.local',
    password: 'Password1',
    about: 'Мастер по изготовлению мебели',
    birthdate: new Date('1983-10-31'),
    gender: Gender.MALE,
    avatar:
      'https://i.pinimg.com/originals/3a/69/68/3a696883cde69524213c569c8013b2c0.jpg',
    role: UserRole.USER,
  },
];